# Generated by Django 2.0.6 on 2018-06-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
    ]
