# Generated by Django 2.0.6 on 2018-06-22 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=500)),
                ('doc_imp', models.CharField(default='yes', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_app.Document')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_app.UserProfileInfo'),
        ),
    ]
