# Generated by Django 2.0.6 on 2018-06-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_auto_20180619_0640'),
        ('form_app', '0002_auto_20180622_0636'),
    ]

    operations = [
    ]
