# Generated by Django 2.0.6 on 2018-06-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0003_merge_20180628_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentinfo',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentinfo',
            name='student',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentInfo',
        ),
    ]
