# Generated by Django 2.0.6 on 2018-06-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0004_auto_20180628_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='librarydue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=20)),
                ('dues', models.IntegerField()),
            ],
        ),
    ]
