# Generated by Django 2.0.6 on 2018-06-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_librarydue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarydue',
            name='id',
        ),
        migrations.AlterField(
            model_name='librarydue',
            name='roll',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
